version: '3.8'

services:
  # Redis para BullMQ e cache
  redis:
    image: redis:7-alpine
    container_name: auzap-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  # PostgreSQL local (opcional - pode usar Supabase Cloud)
  postgres:
    image: postgres:16-alpine
    container_name: auzap-postgres
    environment:
      POSTGRES_DB: auzap_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  # Adminer - UI para PostgreSQL (opcional)
  adminer:
    image: adminer:latest
    container_name: auzap-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    restart: unless-stopped

  # RedisInsight - UI para Redis (opcional)
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: auzap-redis-insight
    ports:
      - "8001:8001"
    volumes:
      - redis-insight-data:/db
    restart: unless-stopped

volumes:
  redis-data:
  postgres-data:
  redis-insight-data:

networks:
  default:
    name: auzap-network
