services:
  - type: web
    name: auzap-api-docker
    runtime: docker
    repo: https://github.com/fellipesaraiva88/auzap-mvp
    region: oregon
    plan: starter
    branch: main
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /health
    envVars:
      - key: SUPABASE_URL
        value: https://cdndnwglcieylfgzbwts.supabase.co
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        value: https://prime-mullet-17029.upstash.io
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: REDIS_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: BAILEYS_SESSION_PATH
        value: /app/sessions
      - key: LOG_LEVEL
        value: info
