name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pre-deploy-checks:
    name: Pre-deployment Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security checks
        run: npm run deploy:security
        continue-on-error: true

      - name: Run deployment checklist
        run: npm run deploy:check
        continue-on-error: true

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: pre-deploy-checks
    environment:
      name: production
      url: https://auzap-api.onrender.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Render Deploy
        run: |
          echo "Render auto-deploys from main branch"
          echo "Deployment will be triggered automatically"
          echo "Monitor deployment at: https://dashboard.render.com"

      - name: Wait for deployment
        run: sleep 60

      - name: Health check
        run: |
          curl --fail --retry 5 --retry-delay 10 \
            https://auzap-api.onrender.com/health || \
            echo "⚠️ Health check failed, please verify deployment manually"

  smoke-tests:
    name: Post-deployment Smoke Tests
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run smoke tests
        run: npm run deploy:smoke
        continue-on-error: true

      - name: Validate production
        run: npm run deploy:validate
        continue-on-error: true

  notify:
    name: Deployment Notification
    runs-on: ubuntu-latest
    needs: [deploy, smoke-tests]
    if: always()

    steps:
      - name: Send success notification
        if: needs.deploy.result == 'success' && needs.smoke-tests.result == 'success'
        run: |
          echo "✅ Deployment successful!"
          echo "Production URL: https://auzap-api.onrender.com"

      - name: Send failure notification
        if: needs.deploy.result == 'failure' || needs.smoke-tests.result == 'failure'
        run: |
          echo "❌ Deployment failed!"
          echo "Please check the logs and rollback if necessary"
